agileway:
  httpclient:
    enabled: true
pip:
  server:
    protocol: https
    nodes:  www.python.org:80
  repositories:
    - name: pipserver
      url: https://www.python.org:80
    - name: local
      url: file://d:/pip_repo
  source: pipserver
  destination: local