agileway:
  httpclient:
    enabled: true

artifact:
  repositories:
    - name: pipserver
      url: https://www.python.org:80
      layout: pypi
    - name: local
      url: file://d:/pip_repo
      layout: local

pypi:
  server:
    protocol: https
    nodes: www.python.org:80
  source: pipserver
  destination: local