agileway:
  httpclient:
    enabled: true
  artifact:
    enabled: true
    repositories:
      - name: pipserver
        url: https://www.python.org:80
        layout: pypi
        supportedDigits: [md5, sha256]
      - name: python_local
        url: file:///d:/pip_repo
        layout: pypi_local

pypi:
  server:
    protocol: https
    nodes: www.python.org:443
  sources: [pipserver]
  destination: python_local